SolutionArtShop/ArtShop.WebSite/Controllers/ArtistController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using Microsoft.AspNet.Identity;
using OdeToFood.WebSite.Controllers;
using OdeToFood.WebSite.Services;
using System;
using System.ComponentModel;
using System.Net;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    public class ArtistController : BaseController
    {
        // GET: Artist

        private BaseDataService<Artist> db;

        public ArtistController()
        {
            db = new BaseDataService<Artist>();
        }
        public ActionResult Index()
        {
            var list = db.Get();
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ABMView()
        {
            var list = db.Get();
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Artist artist)
        {
            this.CheckAuditPattern(artist, true);
            var list = db.ValidateModel(artist);
            if (ModelIsValid(list))
                return View(artist);
            try
            {
                db.Create(artist);
                return RedirectToAction("ABMView");
            }
            catch (System.Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }
            
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                Logger.Instance.LogException(new Exception("Id Artist null "), User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                Logger.Instance.LogException(new Exception("Artist HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            return View(artist);
        }
        [HttpPost]
        public ActionResult Edit(Artist artist)
        {
            this.CheckAuditPattern(artist);
            var list = db.ValidateModel(artist);
            if (ModelIsValid(list))
                return View(artist);
            try
            {
                db.Update(artist);
                return RedirectToAction("ABMView");

            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }

        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                Logger.Instance.LogException(new Exception("Artist HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            try
            {
                db.Delete(artist);
                return RedirectToAction("ABMView");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return RedirectToAction("ABMView");
            }

        }
    }
}

SolutionArtShop/ArtShop.WebSite/Controllers/CartController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using OdeToFood.WebSite.Controllers;
using OdeToFood.WebSite.Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    public class CartController : BaseController
    {
        readonly BaseDataService<CartItem> dbItem;
        readonly BaseDataService<Cart> db;
        readonly BaseDataService<Product> dbProduct;

        public CartController()
        {
            db = new BaseDataService<Cart>();
            dbItem = new BaseDataService<CartItem>();
            dbProduct = new BaseDataService<Product>();
        }
        // GET: Cart
        [Authorize]
        public ActionResult Index()
        {
            if (Request.Cookies["cookieCart"] != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");

                List<CartItem> listaItems = dbItem.Get().Where(x=>x.CartId==Convert.ToInt32(cookie.Value)).ToList();

                foreach(var item in listaItems)
                {
                    item._Product = dbProduct.GetById(item.ProductId);
                }

                return View(listaItems);
            }
            return RedirectToAction("index", "Home");

        }
        [HttpPost]
        public ActionResult AddToCart(int? Id)
        {
            Product oPaint = dbProduct.GetById(Convert.ToInt32(Id));
            if (Id == null)
            {
                Logger.Instance.LogException(new Exception("Id Cart null "), User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Request.Cookies.Get("cookieCart")==null)
            {
                HttpCookie cookie = new HttpCookie("cookieCart");
                Cart oCart = new Cart();

                CartItem oCartItem =new CartItem()
                {
                    ProductId = Convert.ToInt32(Id),
                    Price = oPaint.Price,
                    Quantity = 1,
                    _Product = oPaint
                };
                
                //Seteo datos de cart
                oCart.ItemCount = 1;
                var format = "dd/MM/yyyy HH:mm:ss";
                var hoy = DateTime.Now.ToString(format);
                var dateTime = DateTime.ParseExact(hoy, format, CultureInfo.InvariantCulture);
                oCart.CartDate = dateTime;
                oCart.Cookie = "";
               
                
                    
                this.CheckAuditPattern(oCart, true);
                var list = db.ValidateModel(oCart);

                if (ModelIsValid(list))
                    return RedirectToAction("itemProduct", "Product", new { Id });
                try
                {
                    //Obtengo el id del carritoCreado
                    Cart oCartSave = db.Create(oCart);
                    
                    cookie.Value = oCartSave.Id.ToString();
                    oCartSave.Cookie = cookie.Value;

                    //Actualizo el carrito con la cookie
                    db.Update(oCartSave);

                    //Genero la cookie
                    Response.Cookies.Add(cookie);

                    //Guardo el id del carrito en el item
                    oCartItem.CartId = oCartSave.Id;
                }
                catch (Exception ex)
                {
                    Logger.Instance.LogException(ex, User.Identity.GetUserId());

                }

                this.CheckAuditPattern(oCartItem, true);
                var list2 = dbItem.ValidateModel(oCartItem);

               

                


                if (ModelIsValid(list2))
                    return RedirectToAction("itemProduct", "Product", new { Id });
                try
                {
                    //Guardo el item
                    dbItem.Create(oCartItem);
                    
                    
                }
                catch (Exception ex)
                {
                    Logger.Instance.LogException(ex, User.Identity.GetUserId());
                }
                    
               
               
                
            }
            else
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");
                List<CartItem> listaItems =dbItem.Get().Where(x => x.CartId == Convert.ToInt32(cookie.Value)).ToList();
                 
                CartItem oCartItem = new CartItem()
                {
                    ProductId = Convert.ToInt32(Id),
                    Price = oPaint.Price,
                    Quantity = 1,
                    CartId= Convert.ToInt32(cookie.Value),
                    _Product = oPaint
                };
                
                this.CheckAuditPattern(oCartItem, true);
                var list2 = dbItem.ValidateModel(oCartItem);


                //Actualizo cantidad de items del carrito 
                Cart oCart = db.GetById(Convert.ToInt32(cookie.Value));
                oCart.ItemCount += 1;

                this.CheckAuditPattern(oCart, true);
                var list3 = db.ValidateModel(oCart);

                if (ModelIsValid(list2))
                    return RedirectToAction("itemProduct", "Product", new { Id });
                try
                {
                    //Guardo el item
                    dbItem.Create(oCartItem);
                    db.Update(oCart);
                }
                catch (Exception ex)
                {
                    Logger.Instance.LogException(ex, User.Identity.GetUserId());
                }

            }

            return RedirectToAction("itemProduct", "Product", new { Id });
        }

        public ActionResult DeleteItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var cartItem = dbItem.GetById(id.Value);
            if (cartItem == null)
            {
                Logger.Instance.LogException(new Exception("CartItem HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            try
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");
                Cart oCart = db.GetById(Convert.ToInt32(cookie.Value));
                oCart.ItemCount -= 1;

                dbItem.Delete(cartItem);
                db.Update(oCart);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return RedirectToAction("Index");
            }

        }

        public ActionResult getPrice()
        {
            HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");
            var precio = 0.0;
            if (cookie != null)
            {
                List<CartItem> listaItems = dbItem.Get().Where(x=>x.CartId==Convert.ToInt32(cookie.Value)).ToList();

                foreach (var item in listaItems)
                {
                    precio = precio + item.Price;

                }
            }
            
            return Json(new { response = precio }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult deleteCartItems()
        {
            
            if (Request.Cookies["cookieCart"] != null)
            {

                Response.Cookies["cookieCart"].Expires = DateTime.Now.AddDays(-1);

                HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");

                List<CartItem> listaItems = dbItem.Get().Where(x => x.CartId == Convert.ToInt32(cookie.Value)).ToList();

                foreach (var item in listaItems)
                {
                    dbItem.Delete(item);

                }
                Cart oCart = db.GetById(Convert.ToInt32(cookie.Value));
                db.Delete(oCart);
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult deleteCartItemsAfterSave()
        {

            if (Request.Cookies["cookieCart"] != null)
            {

                Response.Cookies["cookieCart"].Expires = DateTime.Now.AddDays(-1);

                HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");

                List<CartItem> listaItems = dbItem.Get().Where(x => x.CartId == Convert.ToInt32(cookie.Value)).ToList();

                foreach (var item in listaItems)
                {
                    dbItem.Delete(item);

                }
                Cart oCart = db.GetById(Convert.ToInt32(cookie.Value));
                db.Delete(oCart);
            }
            return RedirectToAction("Success");
        }

        public ActionResult Success()
        {
            return View();
        }
        

    }
}

SolutionArtShop/ArtShop.WebSite/Controllers/OrderController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using OdeToFood.WebSite.Controllers;
using OdeToFood.WebSite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    public class OrderController : BaseController
    {
        // GET: Order

        readonly BaseDataService<Order> db;
        readonly BaseDataService<CartItem> dbItem;
        readonly BaseDataService<OrderDetail> dbDetail;
        readonly BaseDataService<Product> dbProduct;

        public OrderController()
        {
            db = new BaseDataService<Order>();
            dbItem = new BaseDataService<CartItem>();
            dbDetail = new BaseDataService<OrderDetail>();
            dbProduct = new BaseDataService<Product>();
        }
            public ActionResult Index()
        {
            var model = db.Get().OrderBy(x=>x.Id).Reverse();
            return View(model);
        }
        [HttpPost]
        public ActionResult SaveOrder(int itemsCount, string totalPrice)
        {
            double precioTotal = Convert.ToDouble(totalPrice.Replace("$", ""));
            if (precioTotal <= 0)
            {
                ViewBag.MessageDanger = "Debe agregar items al carrito";
                return RedirectToAction("Index","home",null);
            }
            else
            {
                Order oOrder = new Order(){
                    UserId=User.Identity.GetUserId(),
                    OrderDate = DateTime.Now,
                    OrderNumber = 1,//DESHARCODEAR
                    ItemCount = itemsCount,
                    TotalPrice = precioTotal

                };
                this.CheckAuditPattern(oOrder, true);
                var list = db.ValidateModel(oOrder);

                if (ModelIsValid(list))
                    return RedirectToAction("Index", "home", null);
                try
                {
                    Order oOrderSave= db.Create(oOrder);

                    HttpCookie cookie = HttpContext.Request.Cookies.Get("cookieCart");

                    List<CartItem> listaItems = dbItem.Get().Where(x => x.CartId == Convert.ToInt32(cookie.Value)).ToList();

                    foreach(var item in listaItems)
                    {

                        //Actualizacion cantidad vendida de producto
                        Product oProducto = dbProduct.GetById(item.ProductId);
                        oProducto.QuantitySold += 1;
                        this.CheckAuditPattern(oProducto, true);
                        var list3 = dbProduct.ValidateModel(oProducto);

                        if (ModelIsValid(list3))
                            return RedirectToAction("Index", "home", null);

                        dbProduct.Update(oProducto);
                        //Alta Detalles de orden
                        OrderDetail oDetail = new OrderDetail()
                        {
                            OrderId = oOrderSave.Id,
                            ProductId=item.ProductId,
                            Price = item.Price,
                            Quantity = item.Quantity
                        };
                        this.CheckAuditPattern(oDetail, true);
                        var list2 = dbDetail.ValidateModel(oDetail);

                        if (ModelIsValid(list2))
                            return RedirectToAction("Index", "home", null);

                        dbDetail.Create(oDetail);
                    }



                }
                catch (Exception ex)
                {
                    Logger.Instance.LogException(ex, User.Identity.GetUserId());

                }

            }
            return RedirectToAction("deleteCartItemsAfterSave", "Cart");

        }

        public ActionResult Pay(int itemsCount, string totalPrice)
        {
            ViewBag.itemsCount = itemsCount;
            ViewBag.totalPrice = totalPrice;
            return View();
        }
        

    }
}

SolutionArtShop/ArtShop.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UAIart</title>
    <link href="~/Content/css/styles.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header id="header">
        <div class="centerHeader">
            <div id="logo">
                <a id="cart" href="@Url.Action("Index","Home")"><img src="~/Content/Images/logoHome.png" /></a>
            </div>

            <nav id="menu">
                <ul>
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-item" })

                    </li>
                    <li>
                        @Html.ActionLink("Pinturas", "Index", "Product", new { area = "" }, new { @class = "nav-item" })
                    </li>
                    <li>
                        @Html.ActionLink("Artistas", "Index", "Artist", new { area = "" }, new { @class = "nav-item" })
                    </li>
                    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                    {
                        <li>
                            @Html.ActionLink("ABM", "ABMView", "Product", new { area = "" }, new { @class = "nav-item" })
                            <ul>
                                <li>
                                    @Html.ActionLink("ABM Pinturas", "ABMView", "Product", new { area = "" }, new { @class = "nav-item" })
                                </li>
                                <li>
                                    @Html.ActionLink("ABM Artistas", "ABMView", "Artist", new { area = "" }, new { @class = "nav-item" })
                                </li>
                            </ul>
                        </li>
                        <li>
                            @Html.ActionLink("Reportes", "Index", "Error", new { area = "" }, new { @class = "nav-item" })
                            <ul>
                                <li>
                                    @Html.ActionLink("Reporte Errores", "Index", "Error", new { area = "" }, new { @class = "nav-item" })
                                </li>
                                <li>
                                    @Html.ActionLink("Reporte Órdenes", "Index", "Order", new { area = "" }, new { @class = "nav-item" })
                                </li>
                            </ul>
                        </li>
                   
                    }


                </ul>
                <span class="nav-indicator"></span>
            </nav>
            <div class="sesion">
                @Html.Partial("_LoginPartial")
            </div>
            <div id="Carrito" class="icon-container">
                <a id="cart" href="@Url.Action("Index","Cart")" data-toggle="popover-cart" data-placement="bottom"><i class="material-icons icon-small">add_shopping_cart</i></a>
                <span id="cartValue" class="spanCart"><strong id="cartPrice"></strong></span>

            </div>
            <div id="popover_content_wrapper" style="display: none">
                <span id="cart_details"></span>
                <div align="right">
                    <a href="@Url.Action("Index","Cart")" class="btn btn-primary" id="check_out_cart">
                        <i class="material-icons icon-tiny">add_shopping_cart</i> Check out
                    </a>
                    <a href="@Url.Action("deleteCartItems","Cart")" class="btn btn-default" id="clear_cart">
                        <i class="icon-tiny material-icons">restore_from_trash</i> Clear
                    </a>
                </div>
            </div>
        </div>
    </header>


    <div class="clearfix"></div>
    <div id="slider" class="slider-big">


        <h1>
            @ViewBag.Title
        </h1>




    </div>
    <div class="clearfix"></div>



    <div class="center">

        @RenderBody()

    </div>
    <div class="clearfix"></div>
    <footer id="footer">
        <div class="center">
            <p>&copy; UAI Software</p>
        </div>
    </footer>
    <script type="text/javascript">

        $(document).ready(function () {

            $.ajax({
            type: "GET",
            url: '@Url.Action("getPrice", "Cart")',

            dataType: 'json',
                success: function (result) {
                    $("#cartPrice").text("$" + result.response);

            }
        });

            $("[data-toggle=popover]").popover();

            $("[data-toggle=popover-cart]").popover({ trigger: "manual", html: true, content: $('#popover_content_wrapper').html(), animation: false })
                .on("mouseenter", function () {
                    var _this = this;
                    $(this).popover("show");
                    $(".popover").on("mouseleave", function () {
                        $(_this).popover('hide');
                    });
                }).on("mouseleave", function () {
                    var _this = this;
                    setTimeout(function () {
                        if (!$(".popover:hover").length) {
                            $(_this).popover("hide");
                        }
                    }, 300);
                });

        });




    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>