SolutionArtShop/ArtShop.WebSite/Controllers/ArtistController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using Microsoft.AspNet.Identity;
using OdeToFood.WebSite.Controllers;
using OdeToFood.WebSite.Services;
using System;
using System.ComponentModel;
using System.Net;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    public class ArtistController : BaseController
    {
        // GET: Artist

        private BaseDataService<Artist> db;

        public ArtistController()
        {
            db = new BaseDataService<Artist>();
        }
        public ActionResult Index()
        {
            var list = db.Get();
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ABMView()
        {
            var list = db.Get();
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Artist artist)
        {
            this.CheckAuditPattern(artist, true);
            var list = db.ValidateModel(artist);
            if (ModelIsValid(list))
                return View(artist);
            try
            {
                db.Create(artist);
                return RedirectToAction("ABMView");
            }
            catch (System.Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }
            
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                Logger.Instance.LogException(new Exception("Id Artist null "), User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                Logger.Instance.LogException(new Exception("Artist HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            return View(artist);
        }
        [HttpPost]
        public ActionResult Edit(Artist artist)
        {
            this.CheckAuditPattern(artist);
            var list = db.ValidateModel(artist);
            if (ModelIsValid(list))
                return View(artist);
            try
            {
                db.Update(artist);
                return RedirectToAction("ABMView");

            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }

        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                Logger.Instance.LogException(new Exception("Artist HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            try
            {
                db.Delete(artist);
                return RedirectToAction("ABMView");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return RedirectToAction("ABMView");
            }

        }
    }
}

SolutionArtShop/ArtShop.WebSite/Controllers/ProductController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using Microsoft.AspNet.Identity;
using OdeToFood.WebSite.Controllers;
using OdeToFood.WebSite.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    public class ProductController : BaseController
    {

        readonly BaseDataService<Product> db;
        readonly BaseDataService<Artist> dbArtist ;

        public ProductController()
        {
            db = new BaseDataService<Product>();
            dbArtist = new BaseDataService<Artist>();
        }
        public ActionResult Index()
        {
            var model = db.Get().OrderBy(x=>x.Id).Reverse();
            foreach (var item in model)
            {
                item.Artista = dbArtist.GetById(Convert.ToInt32(item.ArtistID));
            }
            return View(model);
        }
        public ActionResult itemProduct(int? id)
        {
            if (id == null)
            {
                Logger.Instance.LogException(new Exception("Id Product null "), User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = db.GetById(id.Value);
            product.Artista = dbArtist.GetById(Convert.ToInt32(product.ArtistID));
            if (product == null)
            {
                Logger.Instance.LogException(new Exception("Product HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            return View(product);
            
        }
        [HttpPost]
        public ActionResult itemProduct(Product product)
        {
            return View(product);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult ABMView()
        {
            var list = db.Get();
            foreach(var item in list)
            {
                item.Artista = dbArtist.GetById(Convert.ToInt32(item.ArtistID)); 
            }
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            Product model = new Product()
            {
                Artistas = dbArtist.Get()
            };
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Product pintura, HttpPostedFileBase file)
        {
            
            if (ModelState.IsValid)
            {   
                try
                {
                    if (file.ContentLength > 0)
                    {
                        //Insert Pintura
                        string fileName = Path.GetFileName(file.FileName);
                        string path = Path.Combine(Server.MapPath("~/Content/images/Paints"), fileName);
                        file.SaveAs(path);
                        pintura.Image = file.FileName;
                        this.CheckAuditPattern(pintura, true);
                        var list = db.ValidateModel(pintura);
                        db.Create(pintura);

                        //Actualizar Artista
                        Artist artista = dbArtist.GetById(Convert.ToInt32(pintura.ArtistID));
                        artista.TotalProducts += 1;
                        this.CheckAuditPattern(artista, true);
                        dbArtist.Update(artista);
                        return RedirectToAction("ABMView");
                    }

                }
                catch (System.Exception ex)
                {
                    Logger.Instance.LogException(ex,User.Identity.GetUserId());
                    ViewBag.MessageDanger = ex.Message;
                    return View(pintura);
                }
            }
        
            ViewBag.MessageDanger = "Error al cargar el archivo";
            return View(pintura);
        }

        public ActionResult Edit(int? id)
        {
            BaseDataService<Artist> dbArtist = new BaseDataService<Artist>();
            if (id == null)
            {
                Logger.Instance.LogException(new Exception("Id Paint null "), User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pintura = db.GetById(id.Value);
            if (pintura == null)
            {
                Logger.Instance.LogException(new Exception("Paint HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            pintura.Artistas = dbArtist.Get();
            return View(pintura);
        }
        [HttpPost]
        public ActionResult Edit(Product pintura,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        if (file.ContentLength > 0)
                        {
                            string fileName = Path.GetFileName(file.FileName);
                            string path = Path.Combine(Server.MapPath("~/Content/Images/Paints"), fileName);
                            file.SaveAs(path);
                            pintura.Image = file.FileName;

                            this.CheckAuditPattern(pintura);
                            var list = db.ValidateModel(pintura);

                            db.Update(pintura);
                            return RedirectToAction("ABMView");
                        }
                    }
                    
                    else
                    {
                        this.CheckAuditPattern(pintura);
                        var list = db.ValidateModel(pintura);

                        db.Update(pintura);
                        return RedirectToAction("ABMView");

                    }
                   

                }
                catch (Exception ex)
                {
                    Logger.Instance.LogException(ex, User.Identity.GetUserId());
                    ViewBag.MessageDanger = ex.Message;
                    return View(pintura);
                }
            }
            return View(pintura);

        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pintura = db.GetById(id.Value);
            if (pintura == null)
            {
                Logger.Instance.LogException(new Exception("Paint HttpNotFound"), User.Identity.GetUserId());
                return HttpNotFound();
            }
            try
            {
                if (pintura.QuantitySold > 0)
                {
                    ViewBag.MessageDanger = "No se puede eliminar la pintura porque tiene ventas realizadas";
                    return RedirectToAction("ABMView");
                }
                else
                {
                    db.Delete(pintura);
                    return RedirectToAction("ABMView");
                }
                
               
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex, User.Identity.GetUserId());
                ViewBag.MessageDanger = ex.Message;
                return RedirectToAction("ABMView");
            }

        }
    }
}

SolutionArtShop/ArtShop.WebSite/Views/Artist/ABMView.cshtml
@model IEnumerable<ArtShop.Data.Model.Artist>
@{
    ViewBag.Title = "ABM Artistas";
}


    <div class="formStyle">
        @if (ViewBag.MessageDanger != "" || ViewBag.MessageDanger != null)
        {
            <span class="error">@ViewBag.MessageDanger</span>
        }
        <form>
            <div id="restDiv">
                <div id="artist" class="interiorCard">
                    <a id="linkCrearPaint" href="@Url.Action("Create","Artist")" class="btn btn-outline-success addButton"><i class="material-icons ">add_circle_outline</i>Nuevo Artista</a>
                    <table class="table cart-items">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.FullName)</th>
                                <th>@Html.DisplayNameFor(model => model.Country)</th>
                                <th>@Html.DisplayNameFor(model => model.LifeSpan)</th>
                                <th>@Html.DisplayNameFor(model => model.Description)</th>
                                <th>@Html.DisplayNameFor(model => model.TotalProducts)</th>
                                <th>Acciones</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(model => item.FullName)</td>
                                    <td>@Html.DisplayFor(model => item.Country) </td>
                                    <td>@Html.DisplayFor(model => item.LifeSpan)</td>
                                    <td>@Html.DisplayFor(model => item.Description)</td>
                                    <td>@Html.DisplayFor(model => item.TotalProducts)</td>
                                    <th>
                                        <a href="@Url.Action("Edit", "Artist", new {id=item.Id })"><i class="material-icons icon-small">create</i></a>
                                        @if (item.TotalProducts == 0)
                                        {
                                            <a href="@Url.Action("Delete", "Artist", new { id = item.Id })"><i class="material-icons icon-small">delete_outline</i></a>
                                        }
                                        </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </form>
    </div>

SolutionArtShop/ArtShop.WebSite/Views/Artist/Create.cshtml
@model ArtShop.Data.Model.Artist
@{
    ViewBag.Title = "Crear Artista";
}

@using (Html.BeginForm())
{
    <div class="formStyle">
        <form>
            <div id="restDiv">
                @if (ViewBag.MessageDanger != "" || ViewBag.MessageDanger!= null)
                {
                    <span class="error">@ViewBag.MessageDanger</span>
                }
                <div id="artist" class="interiorCard ">
                    @Html.LabelFor(model => model.FirstName) @Html.EditorFor(model => model.FirstName)
                    @Html.LabelFor(model => model.LastName) @Html.EditorFor(model => model.LastName)
                    @Html.LabelFor(model => model.LifeSpan) @Html.EditorFor(model => model.LifeSpan)
                    @Html.LabelFor(model => model.Country) @Html.EditorFor(model => model.Country)
                    @Html.LabelFor(model => model.Description) @Html.EditorFor(model => model.Description)
                </div>
                <div class="button-section">
                    <input class="btn btn-lg btn-outline-success" type="submit" name="Sign Up" />
                    @Html.ActionLink("Volver a la lista", "ABMView",new { area = "" }, new { @class = "btn btn-lg btn-outline-primary" })

                </div>

            </div>

        </form>
    </div>
}

SolutionArtShop/ArtShop.WebSite/Views/Artist/Edit.cshtml
@model ArtShop.Data.Model.Artist
@{
    ViewBag.Title = "Editar Artista";
}

@using (Html.BeginForm())
{
    <div class="formStyle">
        <form>
            <div id="restDiv">
                @if (ViewBag.MessageDanger != "" || ViewBag.MessageDanger != null)
                {
                    <span class="error">@ViewBag.MessageDanger</span>
                }
            <div id="artist" class="interiorCard ">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreatedOn)
                @Html.HiddenFor(model => model.CreatedBy)
                @Html.HiddenFor(model => model.TotalProducts)
                @Html.LabelFor(model => model.FirstName) @Html.EditorFor(model => model.FirstName)
                @Html.LabelFor(model => model.LastName) @Html.EditorFor(model => model.LastName)
                @Html.LabelFor(model => model.LifeSpan) @Html.EditorFor(model => model.LifeSpan)
                @Html.LabelFor(model => model.Country) @Html.EditorFor(model => model.Country)
                @Html.LabelFor(model => model.Description) @Html.EditorFor(model => model.Description)
            </div>
                <div class="button-section">
                    <input class="btn btn-lg btn-outline-success" type="submit" name="Sign Up" />
                    @Html.ActionLink("Volver a la lista", "ABMView", new { area = "" }, new { @class = "btn btn-lg btn-outline-primary" })

                </div>

            </div>

        </form>
    </div>
}

SolutionArtShop/ArtShop.WebSite/Views/Artist/Index.cshtml
@model IEnumerable<ArtShop.Data.Model.Artist>
@{
    ViewBag.Title = "Artistas";
}

    <div class="contentPage">
        <section class="sectionRight">
            <div class="cardHome">
                @foreach (var item in Model)
                {
                    <div class="cardProp colProp-lg-4">
                        <div class="cardContainer">
                            <h4><b>@Html.DisplayFor(model => item.FullName)</b> </h4>
                            <p>@Html.DisplayNameFor(model => model.Country): @Html.DisplayFor(model => item.Country)</p>
                            <p>@Html.DisplayNameFor(model => model.LifeSpan): @Html.DisplayFor(model => item.LifeSpan)</p>
                            <p>@Html.DisplayNameFor(model => model.TotalProducts): @Html.DisplayFor(model => item.TotalProducts)</p>
                            @*<a href=@Url.Action("itemProduct","Product",@item)><span class="icon-plus">Ver<i class="medium material-icons" style="position: relative;top: 6px;">add_box</i></span></a>*@
                        </div>
                    </div>
                }

            </div>
            @*<span class="spanbtnHome">

                @Html.ActionLink("Ver Más", "Index", "Product", new { area = "" }, new { @class = "btn btn-success btnHome", @style = "line-height: 30px;" })
            </span>*@

        </section>
        <aside>
            SECCION ASIDE
        </aside>
    </div>